/**
 * Auto-generated by scripts/update-news-image-count.ts.
 * Sorted list of sample news images in public/assets/news.
 * Re-run after adding or removing images.
 */
export const LOCAL_NEWS_IMAGE_COUNT = 17;

export const LOCAL_NEWS_IMAGES: string[] = [
  '/assets/news/abigail-keenan-8-s5QuUBtyM-unsplash.jpg',
  '/assets/news/fancy-crave-qowyMze7jqg-unsplash.jpg',
  '/assets/news/mario-klassen-70YxSTWa2Zw-unsplash.jpg',
  '/assets/news/peter-glaser-qWs_Wa1JrKM-unsplash.jpg',
  '/assets/news/pexels-bechir-lachiheb-2148044404-29920213.jpg',
  '/assets/news/pexels-boom-12585891.jpg',
  '/assets/news/pexels-cesar-o-neill-26650613-30393837.jpg',
  '/assets/news/pexels-franco-monsalvo-252430633-32179310.jpg',
  '/assets/news/pexels-franco-monsalvo-252430633-38060743.jpg',
  '/assets/news/pexels-franco-monsalvo-252430633-38092612.jpg',
  '/assets/news/pexels-franco-monsalvo-252430633-38454718.jpg',
  '/assets/news/pexels-franco-monsalvo-252430633-38616125.jpg',
  '/assets/news/pexels-mateo-franciosi-283676800-38259022.jpg',
  '/assets/news/pexels-omar-ramadan-1739260-28355076.jpg',
  '/assets/news/pexels-omar-ramadan-1739260-5886522.jpg',
  '/assets/news/pexels-omar-ramadan-1739260-9405210.jpg',
  '/assets/news/pexels-sinan-kriya-2162662325-38849277.jpg',
];
