import { readdir, writeFile } from 'fs/promises';
import { join } from 'path';

const OUT = join(process.cwd(), 'src', 'lib', 'constants', 'news-image-count.ts');
const DIR = join(process.cwd(), 'public', 'assets', 'news');

const IMAGE_EXT = /\.(jpe?g|png|webp|gif|avif|bmp|svg)$/i;

export async function updateNewsImageCount(): Promise<number> {
  let files: string[] = [];
  try {
    files = await readdir(DIR);
  } catch {
    // Folder missing — that's fine, count stays 0.
  }
  const images = files.filter(f => IMAGE_EXT.test(f)).sort();

  const body = images
    .map((f) => `  '/assets/news/${f}',`)
    .join('\n');

  await writeFile(
    OUT,
    `/**\n * Auto-generated by scripts/update-news-image-count.ts.\n * Sorted list of sample news images in public/assets/news.\n * Re-run after adding or removing images.\n */\nexport const LOCAL_NEWS_IMAGE_COUNT = ${images.length};\n\nexport const LOCAL_NEWS_IMAGES: string[] = [\n${body}\n];\n`,
    'utf-8'
  );
  console.log(`news-image-count.ts → ${images.length} images`);
  return images.length;
}