/**
 * Generates the logo manifest from the files actually present in
 * public/assets/logos/.
 *
 * The manifest is the single source of truth for which local logos exist.
 * The resolver (src/lib/utils/logo-mapping.ts) only ever returns a path that
 * appears in this manifest, so a logo can never be mapped to a file that does
 * not exist.
 *
 * Run: npx tsx scripts/generate-logo-manifest.ts
 */

import { readdirSync, statSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = join(process.cwd(), 'public/assets/logos');
const OUT = join(process.cwd(), 'src/lib/data/logo-manifest.ts');

interface LogoEntry {
  /** Competition folder key, e.g. "premier-league". */
  competition: string;
  /** Full public path, e.g. "/assets/logos/clubs/england/premier-league/arsenal.png". */
  path: string;
  /** Filename without extension, e.g. "arsenal". */
  stem: string;
}

function walk(dir: string, out: LogoEntry[]): void {
  for (const item of readdirSync(dir)) {
    const full = join(dir, item);
    if (statSync(full).isDirectory()) {
      walk(full, out);
      continue;
    }
    if (!/\.(png|svg|jpe?g|webp)$/i.test(item)) continue;

    const rel = relative(ROOT, full).replace(/\\/g, '/');
    const segments = rel.split('/').slice(0, -1);
    const filename = item;
    const stem = item.replace(/\.[^.]+$/, '');
    const competition = segments.length ? segments[segments.length - 1] : '(root)';

    out.push({
      competition,
      path: `/assets/logos/${rel}`,
      stem,
      ...(filename ? {} : {}),
    });
  }
}

if (!existsSync(ROOT)) {
  console.error(`Logo root not found: ${ROOT}`);
  process.exit(1);
}

const entries: LogoEntry[] = [];
walk(ROOT, entries);
entries.sort((a, b) => a.path.localeCompare(b.path));

/**
 * Stem cleanup: uploads arrive as "<team>.football-logos.cc.png", so strip the
 * source-site suffix to get the real team slug.
 */
for (const e of entries) {
  e.stem = e.stem.replace(/\.football-logos\.cc$/, '');
}

/**
 * A club can appear in more than one competition folder (e.g. Arsenal is in
 * both premier-league/ and champions-league/). The crest is the same asset, so
 * the resolver needs one deterministic winner. Domestic leagues win for clubs;
 * the World Cup folder wins for national teams.
 */
const COMPETITION_PRIORITY = [
  'premier-league',
  'la-liga',
  'bundesliga',
  'serie-a',
  'ligue-1',
  'championship',
  '2-bundesliga',
  'world-cup-2026',
  'nations-league',
  'champions-league',
  'europa-league',
  'conference-league',
];

function priority(competition: string): number {
  const i = COMPETITION_PRIORITY.indexOf(competition);
  return i === -1 ? COMPETITION_PRIORITY.length : i;
}

// Detect collisions and keep one asset per stem.
const stemCounts = new Map<string, number>();
for (const e of entries) stemCounts.set(e.stem, (stemCounts.get(e.stem) ?? 0) + 1);
const duplicates = [...stemCounts.entries()].filter(([, n]) => n > 1);

const deduped = new Map<string, LogoEntry>();
for (const e of entries) {
  const existing = deduped.get(e.stem);
  if (!existing || priority(e.competition) < priority(existing.competition)) {
    deduped.set(e.stem, e);
  }
}
const assets = [...deduped.values()].sort((a, b) => a.path.localeCompare(b.path));

const banner = `/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Generated by scripts/generate-logo-manifest.ts from the files present in
 * public/assets/logos/. Regenerate whenever logos are added or removed.
 *
 * ${entries.length} logos across ${new Set(entries.map(e => e.competition)).size} competition folders.
 */
`;

const body = `export interface LogoAsset {
  /** Competition folder the logo lives in. */
  competition: string;
  /** Public path served from public/assets/logos/. */
  path: string;
  /** Filename without extension (the team slug). */
  stem: string;
}

/** Every local logo file, one entry per team slug (duplicates resolved). */
export const LOGO_ASSETS: LogoAsset[] = ${JSON.stringify(assets, null, 2)};

/** Lookup: team slug -> asset. */
export const LOGO_ASSETS_BY_STEM: Record<string, LogoAsset> = Object.fromEntries(
  LOGO_ASSETS.map(a => [a.stem, a])
);
`;

writeFileSync(OUT, banner + body, 'utf-8');

console.log(`Wrote ${OUT}`);
console.log(`  logos on disk:  ${entries.length}`);
console.log(`  unique stems:   ${assets.length}`);
console.log(`  competitions:   ${[...new Set(entries.map(e => e.competition))].sort().join(', ')}`);
if (duplicates.length) {
  console.log(`  duplicate stems (${duplicates.length}) resolved by priority:`);
  for (const [stem] of duplicates) console.log(`    ${stem} -> ${deduped.get(stem)!.competition}`);
}
process.exit(0);
