/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Generated by scripts/generate-logo-manifest.ts from the files present in
 * public/assets/logos/. Regenerate whenever logos are added or removed.
 *
 * 348 logos across 12 competition folders.
 */
export interface LogoAsset {
  /** Competition folder the logo lives in. */
  competition: string;
  /** Public path served from public/assets/logos/. */
  path: string;
  /** Filename without extension (the team slug). */
  stem: string;
}

/** Every local logo file, one entry per team slug (duplicates resolved). */
export const LOGO_ASSETS: LogoAsset[] = [
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/birmingham.png",
    "stem": "birmingham"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/blackburn-rovers.png",
    "stem": "blackburn-rovers"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/bolton.png",
    "stem": "bolton"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/bristol-city.png",
    "stem": "bristol-city"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/burnley.png",
    "stem": "burnley"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/cardiff-city.png",
    "stem": "cardiff-city"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/charlton.png",
    "stem": "charlton"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/derby-county.png",
    "stem": "derby-county"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/lincoln-city.png",
    "stem": "lincoln-city"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/middlesbrough.png",
    "stem": "middlesbrough"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/millwall.png",
    "stem": "millwall"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/norwich-city.png",
    "stem": "norwich-city"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/portsmouth.png",
    "stem": "portsmouth"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/preston-north-end.png",
    "stem": "preston-north-end"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/queens-park-rangers.png",
    "stem": "queens-park-rangers"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/sheffield-united.png",
    "stem": "sheffield-united"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/southampton.png",
    "stem": "southampton"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/stoke-city.png",
    "stem": "stoke-city"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/swansea-city.png",
    "stem": "swansea-city"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/watford.png",
    "stem": "watford"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/west-bromwich-albion.png",
    "stem": "west-bromwich-albion"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/west-ham.png",
    "stem": "west-ham"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/wolves.png",
    "stem": "wolves"
  },
  {
    "competition": "championship",
    "path": "/assets/logos/clubs/england/championship/wrexham.png",
    "stem": "wrexham"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/arsenal.png",
    "stem": "arsenal"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/aston-villa.png",
    "stem": "aston-villa"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/bournemouth.png",
    "stem": "bournemouth"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/brentford.png",
    "stem": "brentford"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/brighton.png",
    "stem": "brighton"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/chelsea.png",
    "stem": "chelsea"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/coventry-city.png",
    "stem": "coventry-city"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/crystal-palace.png",
    "stem": "crystal-palace"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/everton.png",
    "stem": "everton"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/fulham.png",
    "stem": "fulham"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/hull-city.png",
    "stem": "hull-city"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/ipswich.png",
    "stem": "ipswich"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/leeds-united.png",
    "stem": "leeds-united"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/liverpool.png",
    "stem": "liverpool"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/manchester-city.png",
    "stem": "manchester-city"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/manchester-united.png",
    "stem": "manchester-united"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/newcastle.png",
    "stem": "newcastle"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/nottingham-forest.png",
    "stem": "nottingham-forest"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/sunderland.png",
    "stem": "sunderland"
  },
  {
    "competition": "premier-league",
    "path": "/assets/logos/clubs/england/premier-league/tottenham.png",
    "stem": "tottenham"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/angers.png",
    "stem": "angers"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/as-monaco.png",
    "stem": "as-monaco"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/auxerre.png",
    "stem": "auxerre"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/brest.png",
    "stem": "brest"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/le-havre-ac.png",
    "stem": "le-havre-ac"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/le-mans.png",
    "stem": "le-mans"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/lille.png",
    "stem": "lille"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/lorient.png",
    "stem": "lorient"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/lyon.png",
    "stem": "lyon"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/marseille.png",
    "stem": "marseille"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/nice.png",
    "stem": "nice"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/paris-fc.png",
    "stem": "paris-fc"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/paris-saint-germain.png",
    "stem": "paris-saint-germain"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/rc-lens.png",
    "stem": "rc-lens"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/rc-strasbourg-alsace.png",
    "stem": "rc-strasbourg-alsace"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/rennes.png",
    "stem": "rennes"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/toulouse.png",
    "stem": "toulouse"
  },
  {
    "competition": "ligue-1",
    "path": "/assets/logos/clubs/france/ligue-1/troyes.png",
    "stem": "troyes"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/1-fc-magdeburg.png",
    "stem": "1-fc-magdeburg"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/arminia-bielefeld.png",
    "stem": "arminia-bielefeld"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/darmstadt.png",
    "stem": "darmstadt"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/dynamo-dresden.png",
    "stem": "dynamo-dresden"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/eintracht-braunschweig.png",
    "stem": "eintracht-braunschweig"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/energie-cottbus.png",
    "stem": "energie-cottbus"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/fc-heidenheim.png",
    "stem": "fc-heidenheim"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/fc-kaiserslautern.png",
    "stem": "fc-kaiserslautern"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/fc-nurnberg.png",
    "stem": "fc-nurnberg"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/hannover-96.png",
    "stem": "hannover-96"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/hertha-bsc.png",
    "stem": "hertha-bsc"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/holstein-kiel.png",
    "stem": "holstein-kiel"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/karlsruher.png",
    "stem": "karlsruher"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/osnabruck.png",
    "stem": "osnabruck"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/spvgg-greuther-furth.png",
    "stem": "spvgg-greuther-furth"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/st-pauli.png",
    "stem": "st-pauli"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/vfl-bochum.png",
    "stem": "vfl-bochum"
  },
  {
    "competition": "2-bundesliga",
    "path": "/assets/logos/clubs/germany/2-bundesliga/wolfsburg.png",
    "stem": "wolfsburg"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/augsburg.png",
    "stem": "augsburg"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/bayer-leverkusen.png",
    "stem": "bayer-leverkusen"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/bayern-munchen.png",
    "stem": "bayern-munchen"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/borussia-dortmund.png",
    "stem": "borussia-dortmund"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/borussia-monchengladbach.png",
    "stem": "borussia-monchengladbach"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/eintracht-frankfurt.png",
    "stem": "eintracht-frankfurt"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/freiburg.png",
    "stem": "freiburg"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/hamburger-sv.png",
    "stem": "hamburger-sv"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/hoffenheim.png",
    "stem": "hoffenheim"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/koln.png",
    "stem": "koln"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/mainz-05.png",
    "stem": "mainz-05"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/paderborn.png",
    "stem": "paderborn"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/rb-leipzig.png",
    "stem": "rb-leipzig"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/schalke-04.png",
    "stem": "schalke-04"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/sv-elversberg.png",
    "stem": "sv-elversberg"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/union-berlin.png",
    "stem": "union-berlin"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/vfb-stuttgart.png",
    "stem": "vfb-stuttgart"
  },
  {
    "competition": "bundesliga",
    "path": "/assets/logos/clubs/germany/bundesliga/werder-bremen.png",
    "stem": "werder-bremen"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/atalanta.png",
    "stem": "atalanta"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/bologna.png",
    "stem": "bologna"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/cagliari.png",
    "stem": "cagliari"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/como-1907.png",
    "stem": "como-1907"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/fiorentina.png",
    "stem": "fiorentina"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/frosinone.png",
    "stem": "frosinone"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/genoa.png",
    "stem": "genoa"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/inter.png",
    "stem": "inter"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/juventus.png",
    "stem": "juventus"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/lazio.png",
    "stem": "lazio"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/lecce.png",
    "stem": "lecce"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/milan.png",
    "stem": "milan"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/monza.png",
    "stem": "monza"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/napoli.png",
    "stem": "napoli"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/parma.png",
    "stem": "parma"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/roma.png",
    "stem": "roma"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/sassuolo.png",
    "stem": "sassuolo"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/torino.png",
    "stem": "torino"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/udinese.png",
    "stem": "udinese"
  },
  {
    "competition": "serie-a",
    "path": "/assets/logos/clubs/italy/serie-a/venezia.png",
    "stem": "venezia"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/athletic-club.png",
    "stem": "athletic-club"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/atletico-madrid.png",
    "stem": "atletico-madrid"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/barcelona.png",
    "stem": "barcelona"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/celta.png",
    "stem": "celta"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/deportivo-la-coruna.png",
    "stem": "deportivo-la-coruna"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/deportivo.png",
    "stem": "deportivo"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/elche.png",
    "stem": "elche"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/espanyol.png",
    "stem": "espanyol"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/getafe.png",
    "stem": "getafe"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/levante.png",
    "stem": "levante"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/malaga.png",
    "stem": "malaga"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/osasuna.png",
    "stem": "osasuna"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/racing.png",
    "stem": "racing"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/rayo-vallecano.png",
    "stem": "rayo-vallecano"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/real-betis.png",
    "stem": "real-betis"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/real-madrid.png",
    "stem": "real-madrid"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/real-sociedad.png",
    "stem": "real-sociedad"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/sevilla.png",
    "stem": "sevilla"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/valencia.png",
    "stem": "valencia"
  },
  {
    "competition": "la-liga",
    "path": "/assets/logos/clubs/spain/la-liga/villarreal.png",
    "stem": "villarreal"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/albania-national-team.png",
    "stem": "albania-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/andorra-national-team.png",
    "stem": "andorra-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/armenia-national-team.png",
    "stem": "armenia-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/azerbaijan-national-team.png",
    "stem": "azerbaijan-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/belarus-national-team.png",
    "stem": "belarus-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/bulgaria-national-team.png",
    "stem": "bulgaria-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/cyprus-national-team.png",
    "stem": "cyprus-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/denmark-national-team.png",
    "stem": "denmark-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/estonia-national-team.png",
    "stem": "estonia-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/faroe-islands-national-team.png",
    "stem": "faroe-islands-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/finland-national-team.png",
    "stem": "finland-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/georgia-national-team.png",
    "stem": "georgia-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/gibraltar-national-team.png",
    "stem": "gibraltar-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/greece-national-team.png",
    "stem": "greece-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/hungary-national-team.png",
    "stem": "hungary-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/iceland-national-team.png",
    "stem": "iceland-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/israel-national-team.png",
    "stem": "israel-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/italy-national-team.png",
    "stem": "italy-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/kazakhstan-national-team.png",
    "stem": "kazakhstan-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/kosovo-national-team.png",
    "stem": "kosovo-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/latvia-national-team.png",
    "stem": "latvia-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/liechtenstein-national-team.png",
    "stem": "liechtenstein-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/lithuania-national-team.png",
    "stem": "lithuania-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/luxembourg-national-team.png",
    "stem": "luxembourg-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/malta-national-team.png",
    "stem": "malta-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/moldova-national-team.png",
    "stem": "moldova-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/montenegro-national-team.png",
    "stem": "montenegro-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/north-macedonia-national-team.png",
    "stem": "north-macedonia-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/northern-ireland-national-team.png",
    "stem": "northern-ireland-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/poland-national-team.png",
    "stem": "poland-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/republic-of-ireland-national-team.png",
    "stem": "republic-of-ireland-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/romania-national-team.png",
    "stem": "romania-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/san-marino-national-team.png",
    "stem": "san-marino-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/serbia-national-team.png",
    "stem": "serbia-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/slovakia-national-team.png",
    "stem": "slovakia-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/slovenia-national-team.png",
    "stem": "slovenia-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/ukraine-national-team.png",
    "stem": "ukraine-national-team"
  },
  {
    "competition": "nations-league",
    "path": "/assets/logos/international/nations-league/wales-national-team.png",
    "stem": "wales-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/algeria-national-team.png",
    "stem": "algeria-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/argentina-national-team.png",
    "stem": "argentina-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/australia-national-team.png",
    "stem": "australia-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/austria-national-team.png",
    "stem": "austria-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/belgium-national-team.png",
    "stem": "belgium-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/bosnia-and-herzegovina-national-team.png",
    "stem": "bosnia-and-herzegovina-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/brazil-national-team.png",
    "stem": "brazil-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/cabo-verde-national-team.png",
    "stem": "cabo-verde-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/canada-national-team.png",
    "stem": "canada-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/colombia-national-team.png",
    "stem": "colombia-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/congo-dr-national-team.png",
    "stem": "congo-dr-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/cote-d-ivoire-national-team.png",
    "stem": "cote-d-ivoire-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/croatia-national-team.png",
    "stem": "croatia-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/curacao-national-team.png",
    "stem": "curacao-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/czech-republic-national-team.png",
    "stem": "czech-republic-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/dutch-national-team.png",
    "stem": "dutch-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/ecuador-national-team.png",
    "stem": "ecuador-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/egypt-national-team.png",
    "stem": "egypt-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/england-national-team.png",
    "stem": "england-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/france-national-team.png",
    "stem": "france-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/germany-national-team.png",
    "stem": "germany-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/ghana-national-team.png",
    "stem": "ghana-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/haiti-national-team.png",
    "stem": "haiti-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/iran-national-team.png",
    "stem": "iran-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/iraq-national-team.png",
    "stem": "iraq-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/japan-national-team.png",
    "stem": "japan-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/jordan-national-team.png",
    "stem": "jordan-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/mexico-national-team.png",
    "stem": "mexico-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/morocco-national-team.png",
    "stem": "morocco-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/new-zealand-national-team.png",
    "stem": "new-zealand-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/norway-national-team.png",
    "stem": "norway-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/panama-national-team.png",
    "stem": "panama-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/paraguay-national-team.png",
    "stem": "paraguay-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/portuguese-football-federation.png",
    "stem": "portuguese-football-federation"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/qatar-national-team.png",
    "stem": "qatar-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/saudi-arabia-national-team.png",
    "stem": "saudi-arabia-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/scotland-national-team.png",
    "stem": "scotland-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/senegal-national-team.png",
    "stem": "senegal-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/south-africa-national-team.png",
    "stem": "south-africa-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/south-korea-national-team.png",
    "stem": "south-korea-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/spain-national-team.png",
    "stem": "spain-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/sweden-national-team.png",
    "stem": "sweden-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/switzerland-national-team.png",
    "stem": "switzerland-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/tunisia-national-team.png",
    "stem": "tunisia-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/turkey-national-team.png",
    "stem": "turkey-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/uruguay-national-team.png",
    "stem": "uruguay-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/usa-national-team.png",
    "stem": "usa-national-team"
  },
  {
    "competition": "world-cup-2026",
    "path": "/assets/logos/international/world-cup-2026/uzbekistan-national-team.png",
    "stem": "uzbekistan-national-team"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/aek-athens.png",
    "stem": "aek-athens"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/bodo-glimt.png",
    "stem": "bodo-glimt"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/club-brugge.png",
    "stem": "club-brugge"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/fc-porto.png",
    "stem": "fc-porto"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/fenerbahce.png",
    "stem": "fenerbahce"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/feyenoord.png",
    "stem": "feyenoord"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/galatasaray.png",
    "stem": "galatasaray"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/lask.png",
    "stem": "lask"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/psv.png",
    "stem": "psv"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/s-bratislava.png",
    "stem": "s-bratislava"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/sabah.png",
    "stem": "sabah"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/shakhtar.png",
    "stem": "shakhtar"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/slavia-praha.png",
    "stem": "slavia-praha"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/sporting-cp.png",
    "stem": "sporting-cp"
  },
  {
    "competition": "champions-league",
    "path": "/assets/logos/uefa/champions-league/viking.png",
    "stem": "viking"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/agf.png",
    "stem": "agf"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/ajax.png",
    "stem": "ajax"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/borac.png",
    "stem": "borac"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/brann.png",
    "stem": "brann"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/copenhagen.png",
    "stem": "copenhagen"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/crvena-zvezda.png",
    "stem": "crvena-zvezda"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/cska-sofia.png",
    "stem": "cska-sofia"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/egnatia.png",
    "stem": "egnatia"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/gent.png",
    "stem": "gent"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/hajduk-split.png",
    "stem": "hajduk-split"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/hearts.png",
    "stem": "hearts"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/iberia.png",
    "stem": "iberia"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/inter-escaldes.png",
    "stem": "inter-escaldes"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/jablonec.png",
    "stem": "jablonec"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/kairat.png",
    "stem": "kairat"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/kauno-zalgiris.png",
    "stem": "kauno-zalgiris"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/kups.png",
    "stem": "kups"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/lincoln-red-imps.png",
    "stem": "lincoln-red-imps"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/lugano.png",
    "stem": "lugano"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/midtjylland.png",
    "stem": "midtjylland"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/mjallby.png",
    "stem": "mjallby"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/nordsjaelland.png",
    "stem": "nordsjaelland"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/pafos.png",
    "stem": "pafos"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/panathinaikos.png",
    "stem": "panathinaikos"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/riga.png",
    "stem": "riga"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/sc-braga.png",
    "stem": "sc-braga"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/sint-truidense.png",
    "stem": "sint-truidense"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/thun.png",
    "stem": "thun"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/trabzonspor.png",
    "stem": "trabzonspor"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/twente.png",
    "stem": "twente"
  },
  {
    "competition": "conference-league",
    "path": "/assets/logos/uefa/conference-league/u-craiova.png",
    "stem": "u-craiova"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/anderlecht.png",
    "stem": "anderlecht"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/ararat-armenia.png",
    "stem": "ararat-armenia"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/az-alkmaar.png",
    "stem": "az-alkmaar"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/benfica.png",
    "stem": "benfica"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/besiktas.png",
    "stem": "besiktas"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/celje.png",
    "stem": "celje"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/celtic.png",
    "stem": "celtic"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/dinamo-zagreb.png",
    "stem": "dinamo-zagreb"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/ferencvaros.png",
    "stem": "ferencvaros"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/hapoel-beer-sheva.png",
    "stem": "hapoel-beer-sheva"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/jagiellonia.png",
    "stem": "jagiellonia"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/lech-poznan.png",
    "stem": "lech-poznan"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/levski.png",
    "stem": "levski"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/lillestrom.png",
    "stem": "lillestrom"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/nec-nijmegen.png",
    "stem": "nec-nijmegen"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/ofi.png",
    "stem": "ofi"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/olympiacos.png",
    "stem": "olympiacos"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/omonoia.png",
    "stem": "omonoia"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/salzburg.png",
    "stem": "salzburg"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/sparta-praha.png",
    "stem": "sparta-praha"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/sturm-graz.png",
    "stem": "sturm-graz"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/torreense.png",
    "stem": "torreense"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/union-saint-gilloise.png",
    "stem": "union-saint-gilloise"
  },
  {
    "competition": "europa-league",
    "path": "/assets/logos/uefa/europa-league/viktoria-plzen.png",
    "stem": "viktoria-plzen"
  }
];

/** Lookup: team slug -> asset. */
export const LOGO_ASSETS_BY_STEM: Record<string, LogoAsset> = Object.fromEntries(
  LOGO_ASSETS.map(a => [a.stem, a])
);
